name: modddels_annotation_fpdart
description: Annotations for the modddels code-generator when using fpdart.
version: 0.2.0
homepage: https://www.modddels.dev
repository: https://github.com/codingSoot/modddels
funding:
  - https://www.buymeacoffee.com/codingsoot

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  dartz: ^0.10.1
  equatable: ^2.0.5
  fpdart: ^1.1.0
  kt_dart: ^1.1.0
  meta: ^1.9.1
  modddels_annotation_internal: ^0.2.0
  test: ^1.24.4

dev_dependencies:
  lints: ^2.1.1
