name: example
description: A simple modddels usage example.
version: 1.0.0
environment:
  sdk: ">=2.18.0 <3.0.0"
publish_to: none

dependencies:
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  # modddels_annotation_dartz:
    # path: ../../modddels_annotation_dartz
  modddels_annotation_fpdart:
    path: ../../modddels_annotation_fpdart

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.3
  lints: ^2.0.1
  modddels:
    path: ../
  test: ^1.22.2
