name: modddels_annotation_internal
description: Internal annotations for the modddels code-generator. Do not import.
version: 0.1.0
homepage: https://www.modddels.dev
repository: https://github.com/codingSoot/modddels
funding:
  - https://www.buymeacoffee.com/codingsoot

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  characters: ^1.3.0
  collection: ^1.17.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  checks: ^0.2.2
  freezed: ^2.3.3
  lints: ^2.0.1
  test: ^1.22.2
