name: modddels
description: Generate robust, self-validated models with compile-safe states,
  seamless failure handling and easy unit-testing.
version: 0.1.5
homepage: https://www.modddels.dev
repository: https://github.com/codingSoot/modddels
funding:
  - https://www.buymeacoffee.com/codingsoot

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  collection: ^1.17.2
  fpdart: ^0.6.0
  meta: ^1.9.1
  modddels_annotation_internal: ^0.1.0
  recursive_regex: ^1.0.0
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.0
  checks: ^0.2.2
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  lints: ^2.1.1
  modddels_annotation_dartz:
    path: ../modddels_annotation_dartz
  modddels_annotation_fpdart:
    path: ../modddels_annotation_fpdart
  package_config: ^2.1.0
  source_gen_test: ^1.0.6
  test: ^1.24.4
